;-------------------------------------------;
;Creado por: Mario Lara Molina              ;
;Fecha de creación: 07/11/2020              ;
;Última modificación: 07/11/2020            ;
;Forma de compilación:                      ;
; Debe ingresar en la línea de comando      ;
;  Usando el turbo assembler de borland 4:  ;
;          compilar PEP                     ;
;  Y si desea solo ejecutarlo:              ;
;          PEP                              ;
;-------------------------------------------;
